# Generated by Django 3.2.4 on 2021-06-17 06:38

import KDA_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=300)),
                ('state', models.CharField(blank=True, max_length=300, null=True)),
                ('city', models.CharField(max_length=300)),
                ('street', models.CharField(max_length=300)),
                ('block', models.CharField(blank=True, max_length=300, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=300, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_user', models.CharField(max_length=300)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('modified_user', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('mobile_phone_1', models.PositiveIntegerField()),
                ('mobile_phone_2', models.PositiveIntegerField(blank=True, null=True)),
                ('work_phone', models.PositiveIntegerField(blank=True, null=True)),
                ('extension', models.PositiveIntegerField(blank=True, null=True)),
                ('web_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_user', models.CharField(max_length=300)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('modified_user', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=300)),
                ('institution_name', models.CharField(blank=True, max_length=300, null=True)),
                ('specialization', models.CharField(blank=True, max_length=300, null=True)),
                ('remark', models.CharField(blank=True, max_length=300, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_user', models.CharField(max_length=300)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('modified_user', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hosted_Centre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('active', models.BooleanField()),
                ('status', models.PositiveIntegerField()),
                ('effective_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('spoc_id', models.PositiveIntegerField()),
                ('address_id', models.PositiveIntegerField()),
                ('contact_id', models.PositiveIntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_user', models.CharField(max_length=300)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('modified_user', models.CharField(blank=True, max_length=300, null=True)),
                ('channel_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_user', models.CharField(max_length=300)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('modified_user', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_user', models.CharField(max_length=300)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('modified_user', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='person',
            old_name='created',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='modified',
            new_name='modified_date',
        ),
    ]
