# Generated by Django 3.2.4 on 2021-06-18 10:03

import KDA_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0007_auto_20210618_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hosted_Centres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centre_name', models.CharField(max_length=300)),
                ('hc_logo', models.ImageField(upload_to=KDA_app.models.Hosted_Centres.get_upload_path_hc_logo)),
                ('hc_document', models.FileField(upload_to=KDA_app.models.Hosted_Centres.get_upload_path_hc_document)),
                ('qualification', models.CharField(max_length=300)),
                ('institute', models.CharField(max_length=300)),
                ('spoc_f_name', models.CharField(max_length=300, verbose_name='SPOC first name')),
                ('spoc_l_name', models.CharField(max_length=300, verbose_name='SPOC last name')),
                ('spoc_profile_pic', models.ImageField(upload_to=KDA_app.models.Hosted_Centres.get_upload_path_spoc_profile_pic)),
                ('country', models.CharField(max_length=300)),
                ('state', models.CharField(blank=True, max_length=300, null=True)),
                ('city', models.CharField(max_length=300)),
                ('street', models.CharField(max_length=300)),
                ('block', models.CharField(blank=True, max_length=300, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.IntegerField()),
                ('extension_number', models.IntegerField()),
                ('office_number', models.IntegerField()),
            ],
        ),
    ]
