# Generated by Django 3.2.4 on 2021-06-18 10:49

import KDA_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0009_auto_20210618_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosted_centres',
            name='block',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='hosted_centres',
            name='hc_document',
            field=models.FileField(blank=True, null=True, upload_to=KDA_app.models.Hosted_Centres.get_upload_path_hc_document),
        ),
        migrations.AlterField(
            model_name='hosted_centres',
            name='institute',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='hosted_centres',
            name='qualification',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='hosted_centres',
            name='spoc_extension_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hosted_centres',
            name='spoc_office_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hosted_centres',
            name='spoc_profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=KDA_app.models.Hosted_Centres.get_upload_path_spoc_profile_pic),
        ),
        migrations.AlterField(
            model_name='hosted_centres',
            name='state',
            field=models.CharField(max_length=300),
        ),
    ]
