# Generated by Django 3.2.4 on 2021-06-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0010_auto_20210618_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosted_centres',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
