# Generated by Django 3.2.4 on 2021-06-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0012_alter_hosted_centres_centre_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='address',
        ),
        migrations.RemoveField(
            model_name='person',
            name='appointment_id',
        ),
        migrations.RemoveField(
            model_name='person',
            name='channel_id',
        ),
        migrations.RemoveField(
            model_name='person',
            name='child_id',
        ),
        migrations.RemoveField(
            model_name='person',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='person',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='person',
            name='created_user',
        ),
        migrations.RemoveField(
            model_name='person',
            name='education',
        ),
        migrations.RemoveField(
            model_name='person',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='hosted_centre',
        ),
        migrations.RemoveField(
            model_name='person',
            name='individual_id',
        ),
        migrations.RemoveField(
            model_name='person',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='person',
            name='modified_user',
        ),
        migrations.RemoveField(
            model_name='person',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='role',
        ),
        migrations.RemoveField(
            model_name='person',
            name='status',
        ),
        migrations.RemoveField(
            model_name='person',
            name='student_status',
        ),
        migrations.AddField(
            model_name='person',
            name='block',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.CharField(default='qw', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='country',
            field=models.CharField(default='qw', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(default='asas@ass.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='institute',
            field=models.CharField(default='asas', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='mobile_number',
            field=models.IntegerField(default=213123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='postal_code',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='qualification',
            field=models.CharField(default='asa', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='state',
            field=models.CharField(default='as', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='street',
            field=models.CharField(default='asas', max_length=300),
            preserve_default=False,
        ),
    ]
