# Generated by Django 3.2.4 on 2021-06-19 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0014_auto_20210618_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='KDA_app.role'),
        ),
    ]
