# Generated by Django 3.2.4 on 2021-06-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0015_person_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
