# Generated by Django 3.2.4 on 2021-06-19 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0017_auto_20210619_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=300)),
                ('father_name', models.CharField(max_length=300)),
                ('dob', models.DateField()),
                ('appointment_time', models.DateField()),
                ('contact_number', models.IntegerField()),
                ('guardian_name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('class_name', models.CharField(max_length=300)),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
