# Generated by Django 3.2.4 on 2021-06-21 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0021_auto_20210620_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='availability',
        ),
        migrations.AddField(
            model_name='person',
            name='availability',
            field=models.ManyToManyField(blank=True, null=True, to='KDA_app.Availability'),
        ),
    ]
