# Generated by Django 3.2.4 on 2021-06-21 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0023_auto_20210621_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='child_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='guardian_name',
        ),
        migrations.AddField(
            model_name='appointment',
            name='child',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='appointmentt', to='KDA_app.person'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='psychologist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to=settings.AUTH_USER_MODEL),
        ),
    ]
