# Generated by Django 3.2.4 on 2021-06-21 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0024_auto_20210621_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='psychologist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avail', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=200)),
                ('s_time', models.TimeField()),
                ('e_time', models.TimeField()),
                ('available', models.BooleanField()),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
