# Generated by Django 3.2.4 on 2021-06-21 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0026_alter_slot_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='f_available_time_from',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='f_available_time_to',
        ),
    ]
