# Generated by Django 3.2.4 on 2021-06-22 06:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0027_auto_20210621_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_e_time',
            field=models.TimeField(default=datetime.time(6, 7, 38, 729280)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_s_time',
            field=models.TimeField(default=datetime.time(6, 7, 40, 675921)),
            preserve_default=False,
        ),
    ]
