# Generated by Django 3.2.4 on 2021-06-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0031_auto_20210627_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child_case_data',
            name='age_problem',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
