# Generated by Django 3.2.4 on 2021-06-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0032_alter_child_case_data_age_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child_case_data',
            name='age_problem',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
