# Generated by Django 3.2.4 on 2021-06-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0038_auto_20210630_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher_occupied_slots',
            old_name='slot_s_t',
            new_name='slot_time',
        ),
        migrations.AddField(
            model_name='teacher_occupied_slots',
            name='slot_day',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
