# Generated by Django 3.2.4 on 2021-06-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KDA_app', '0039_auto_20210630_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='time',
            field=models.CharField(max_length=200),
        ),
    ]
